/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE filmBaseService PLEASE EDIT ../film.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Film } from '../../domain/manage_film_example_db/film';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Film.service.ts
 */

/*
 * SCHEMA DB Film
 *
	{
		genre: {
			type: 'String',
			enum : ["Action","Crime","Fantasy","Horror"]
		},
		title: {
			type: 'String',
			required : true
		},
		year: {
			type: 'Number'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		cast: [{
			type: Schema.ObjectId,
			ref : "Film"
		}],
		filmMaker: {
			type: Schema.ObjectId,
			required : true,
			ref : "Film"
		},
	}
 *
 */
@Injectable()
export class FilmBaseService {

    contextUrl: string = environment.endpoint + '/films';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * FilmService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Film): Observable<Film> {
        return this.http
            .post<Film>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * FilmService.delete
    *   @description CRUD ACTION delete
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * FilmService.findBycast
    *   @description CRUD ACTION findBycast
    *
    */
    findByCast(id: string): Observable<Film[]> {
        return this.http
            .get<Film[]>(this.contextUrl + '/findBycast/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * FilmService.findByfilmMaker
    *   @description CRUD ACTION findByfilmMaker
    *
    */
    findByFilmMaker(id: string): Observable<Film[]> {
        return this.http
            .get<Film[]>(this.contextUrl + '/findByfilmMaker/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * FilmService.get
    *   @description CRUD ACTION get
    *
    */
    get(id: string): Observable<Film> {
        return this.http
            .get<Film>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * FilmService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Film[]> {
        return this.http
            .get<Film[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * FilmService.update
    *   @description CRUD ACTION update
    *
    */
    update(item: Film): Observable<Film> {
        return this.http
            .post<Film>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
