/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE film-makerBaseService PLEASE EDIT ../film-maker.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { FilmMaker } from '../../domain/manage_film_example_db/film-maker';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../FilmMaker.service.ts
 */

/*
 * SCHEMA DB FilmMaker
 *
	{
		name: {
			type: 'String',
			required : true
		},
		surname: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		filmMaker: {
			type: Schema.ObjectId,
			required : true,
			ref : "Film"
		},
	}
 *
 */
@Injectable()
export class FilmMakerBaseService {

    contextUrl: string = environment.endpoint + '/filmmakers';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * FilmMakerService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: FilmMaker): Observable<FilmMaker> {
        return this.http
            .post<FilmMaker>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * FilmMakerService.delete
    *   @description CRUD ACTION delete
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * FilmMakerService.get
    *   @description CRUD ACTION get
    *
    */
    get(id: string): Observable<FilmMaker> {
        return this.http
            .get<FilmMaker>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * FilmMakerService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<FilmMaker[]> {
        return this.http
            .get<FilmMaker[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * FilmMakerService.update
    *   @description CRUD ACTION update
    *
    */
    update(item: FilmMaker): Observable<FilmMaker> {
        return this.http
            .post<FilmMaker>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
